=== YougaKing/dailyyoga_plugin/app/droidAssist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd" />
    <xs:element name="DailyyogaMIIT">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="Global" />
                <xs:element minOccurs="0" ref="Replace" />
                <xs:element minOccurs="0" ref="Insert" />
                <xs:element minOccurs="0" ref="Enhance" />
            </xs:sequence>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="Global">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Filter" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Replace">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="MethodCall" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="MethodCall">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Source" />
                <xs:element ref="Target" />
                <xs:element minOccurs="0" ref="Filter" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Insert">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="BeforeMethodExecution" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="BeforeMethodExecution">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Source" />
                <xs:element ref="Target" />
                <xs:element minOccurs="0" ref="Filter" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Enhance">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="TryCatchMethodCall" />
                <xs:element minOccurs="0" ref="TryCatchMethodExecution" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="TryCatchMethodCall">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Source" />
                <xs:element ref="Target" />
                <xs:element minOccurs="0" ref="Filter" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="TryCatchMethodExecution">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Source" />
                <xs:element ref="Exception" />
                <xs:element ref="Target" />
                <xs:element minOccurs="0" ref="Filter" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Filter">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Exclude" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Exclude" type="xs:string" />
    <xs:element name="Source">
        <xs:complexType mixed="true">
            <xs:attribute name="extend" default="false" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    <xs:element name="Target" type="xs:string" />
    <xs:element name="Exception" type="xs:string" />
</xs:schema>

=== YougaKing/dailyyoga_plugin/app/droidAssist.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<DailyyogaMIIT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="droidAssist.xsd">
    <Global>
        <Filter>
            <Exclude>com.dailyyoga.plugin.droidassist.LogTransform</Exclude>
            <Exclude>com.dailyyoga.plugin.droidassist.ReflectionTransform</Exclude>
            <Exclude>com.dailyyoga.plugin.droidassist.PrivacyApiTransform</Exclude>
            <Exclude>android.*</Exclude>
            <Exclude>com.android.*</Exclude>
            <Exclude>okhttp3.*</Exclude>
            <Exclude>com.xiaomi.account.openauth.internal.MiAccountPhoneInfo</Exclude>
        </Filter>
    </Global>

    <Replace>
        <MethodCall>
            <Source>
                int android.util.Log.v(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.miit.LogTransform.v($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.v(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.v($$$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                int android.util.Log.d(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.d($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.d(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.d($$$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                int android.util.Log.i(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.i($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.i(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.i($$$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                int android.util.Log.w(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.w($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.w(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.w($$$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.w(java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.w($$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                int android.util.Log.e(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.e($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.e(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.e($$$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                int android.util.Log.wtf(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.wtf($$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.wtf(java.lang.String,java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.wtf($$$);
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                int android.util.Log.wtf(java.lang.String,java.lang.Throwable)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.LogTransform.wtf($$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.Object
                java.lang.reflect.Method.invoke(java.lang.Object,java.lang.Object[])
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.ReflectionTransform.invoke($$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                android.location.Location
                android.location.LocationManager.getLastKnownLocation(java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getLastKnownLocation($);
            </Target>
            <Filter>
                <Exclude>com.alipay.security.mobile.module.deviceinfo.e</Exclude>
            </Filter>
        </MethodCall>

        <MethodCall>
            <Source>
                java.util.List android.content.pm.PackageManager.getInstalledPackages(int)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getInstalledPackages($);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.util.List android.content.pm.PackageManager.getInstalledApplications()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getInstalledApplications();
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                android.provider.Settings$Secure.getString(android.content.ContentResolver,java.lang.String)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getString($$);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                android.telephony.TelephonyManager.getDeviceId()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getDeviceId();
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                java.lang.String
                android.telephony.TelephonyManager.getDeviceId(int)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getDeviceId($);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                android.telephony.TelephonyManager.getImei()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getImei();
            </Target>
        </MethodCall>
        <MethodCall>
            <Source>
                java.lang.String
                android.telephony.TelephonyManager.getImei(int)
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getImei($);
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                android.telephony.TelephonyManager.getSubscriberId()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getSubscriberId();
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                android.net.wifi.WifiInfo.getMacAddress()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getMacAddress();
            </Target>
        </MethodCall>

        <MethodCall>
            <Source>
                java.lang.String
                java.net.NetworkInterface.getHardwareAddress()
            </Source>
            <Target>
                $_= com.dailyyoga.plugin.droidassist.PrivacyApiTransform.getHardwareAddress();
            </Target>
        </MethodCall>
    </Replace>

</DailyyogaMIIT>
